[project]
name = "perplexica-backend"
version = "0.1.0"
description = "Backend service for Perplexica"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta" 